### ISSUE TITLE
About the fork

### ISSUE THREAD

**Issue by mallowigi** [Janrupf/material-theme-jetbrains#1]
I have no qualms of you forking the project, after all it was an open source project until now so according to the MIT License it can be distributed as long as you start maintaining it; however:

- Please do not remove me or Chris from the authors
- Please include a link to the original project
- Please use a name different from the original. Something like "Community Material Theme" should be fine.
- Please use a logo different from the original.
- And it's just my personal request, but I'd appreciate if you could keep the links to the OpenCollective/PayPal (you can add yours though)

Thanks

**Comment by Janrupf** [comment]
Hello, sorry for the late response, it took me quite some while to see your issue. I will work on fulfilling the above points.

**Comment by Janrupf** [comment]
https://github.com/Janrupf/material-theme-jetbrains/commit/47dc84a360ae29106bb61f3361d858763b9bab8a should address the requested changes - I hope I got every file that needed to change.

And thanks for maintaining the original plugin.
