### ISSUE TITLE
[Repo Suggestion] Searchability

### ISSUE THREAD

**Issue by halotroop2288** [Janrupf/material-theme-jetbrains#2]
### Suggestion

1. The Community Material Theme repository is currently very unsearchable
	to those who don't [already have it starred](https://github.com/Janrupf/material-theme-jetbrains/stargazers), or use [Useful Forks](https://useful-forks.github.io/?repo=ChrisRM%2Fmaterial-theme-jetbrains).
2. This could be alleviated by changing the name of the repository to reflect it's uniqueness.
3. I would recommend `community-material-theme-jetbrains` (or something shorter)
4. This would make searching for this free alternative much easier for users like myself.

Thank your for your consideration.

**Comment by Janrupf** [comment]
Yep, good idea.

Done :+1:
