### ISSUE TITLE
State of this project

### ISSUE THREAD

**Issue by satsen** [Janrupf/material-theme-jetbrains#3]
Hello, can you please update this plugin for the new IntelliJ version. Just changing the manifest did not work so I guess the code must be updated as well.

**Comment by halotroop2288** [comment]
Bump. This may just work by changing the metadata! Please make a new release!

**Comment by halotroop2288** [comment]
Maybe just rename this issue to "Update to Latest Version of IntelliJ"...

**Comment by satsen** [comment]
@halotroop2288 In my initial comment I said "Just changing the manifest did not work so I guess the code must be updated as well.", so a metadata change won't suffice. The author seems to have gone inactive on GitHub in general, but for some reason the editor color scheme didn't disappear with the update, so I use that and it's enough for me now.

**Comment by satsen** [comment]
@Janrupf

**Comment by Janrupf** [comment]
Alright, explanation time.

I'm currently not super interested in maintaining this further. My initial plan has always been to patch the project as long as it requires only minimal effort and keeps working. We have now reached a state where the old code with all its hacks simply does not work on newer IntelliJ versions.

Porting the code is not impossible, but certainly a huge amount of work. At the moment I do not feel like I have the resources to perform this work - I'm really busy with other things and the code quality inherited from the original plugin was not good to begin with. Simply put: I'm lacking the motiviation to further port this project. I honestly didn't anticipate that anyone other than me would use it at all.

I'm currently just using the free version of the official plugin, as it still provides all the features I need (this being Atom One Dark).

That being said, I understand that there are people who want to keep using this version of the plugin. If someone is interested in porting this plugin to a new version of IntelliJ, I am willing to assist or transfer the repository if desired.
